# デｰタの読み込み

In [91]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression as LR
train = pd.read_csv("train.csv",index_col = 0)
test = pd.read_csv("test.csv",index_col = 0)
sample = pd.read_csv("sample.csv", header = None)
#sample = pd.read_csv("sample.csv", header = None, delim_whitespace=True, decimal=',')


# データの型の確認

In [92]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 207 entries, 2013-11-18 to 2014-9-30
Data columns (total 11 columns):
y                207 non-null int64
week             207 non-null object
soldout          207 non-null int64
name             207 non-null object
kcal             166 non-null float64
remarks          21 non-null object
event            14 non-null object
payday           10 non-null float64
weather          207 non-null object
precipitation    207 non-null object
temperature      207 non-null float64
dtypes: float64(3), int64(2), object(6)
memory usage: 19.4+ KB


# 各列に欠損値が1つ以上あるか確認

In [93]:
train.isnull().any()

y                False
week             False
soldout          False
name             False
kcal              True
remarks           True
event             True
payday            True
weather          False
precipitation    False
temperature      False
dtype: bool

# 各列に欠損値が幾つあるか

In [94]:
train.isnull().sum()

y                  0
week               0
soldout            0
name               0
kcal              41
remarks          186
event            193
payday           197
weather            0
precipitation      0
temperature        0
dtype: int64

# 欠損値の処理

In [95]:
train.fillna(0).head()
#train["precipitation"] = train["precipitation"].replace("--", "0"))
#train["payday"] = train["payday"].fillna(0)
#train["precipitation"] = train["precipitation"].apply(lambda x : -1 if x == "--" else float(x))
#train["event"] = train["event"].fillna("なし")
#train["remarks"] = train["remarks"].fillna("なし")
#train["month"] = train["datetime"].apply(lambda x : int(x.split("-")[1]))                                          

y week  soldout        name  kcal remarks event  payday weather  \
datetime                                                                        
2013-11-18   90    月        0    厚切りイカフライ   0.0       0     0     0.0      快晴   
2013-11-19  101    火        1     手作りヒレカツ   0.0       0     0     0.0      快晴   
2013-11-20  118    水        0  白身魚唐揚げ野菜あん   0.0       0     0     0.0      快晴   
2013-11-21  120    木        1      若鶏ピリ辛焼   0.0       0     0     0.0      快晴   
2013-11-22  130    金        1    ビッグメンチカツ   0.0       0     0     0.0      快晴   

           precipitation  temperature  
datetime                               
2013-11-18            --         19.8  
2013-11-19            --         17.0  
2013-11-20            --         15.5  
2013-11-21            --         15.2  
2013-11-22            --         16.1

# trainのweekの各値がいくつあるか？

In [96]:
train["week"].value_counts()

水    43
木    43
火    41
金    41
月    39
Name: week, dtype: int64

# trainのweekにダミ－変数を代入

In [97]:
pd.get_dummies(train["week"]).head()

月  木  水  火  金
datetime                 
2013-11-18  1  0  0  0  0
2013-11-19  0  0  0  1  0
2013-11-20  0  0  1  0  0
2013-11-21  0  1  0  0  0
2013-11-22  0  0  0  0  1

# trainのweatrherにダミ－変数を代入

In [98]:
pd.get_dummies(train["weather"]).head()

快晴  晴れ  曇  薄曇  雨  雪  雷電
datetime                           
2013-11-18   1   0  0   0  0  0   0
2013-11-19   1   0  0   0  0  0   0
2013-11-20   1   0  0   0  0  0   0
2013-11-21   1   0  0   0  0  0   0
2013-11-22   1   0  0   0  0  0   0

In [99]:
pd.get_dummies(train["weather"]).tail()

快晴  晴れ  曇  薄曇  雨  雪  雷電
datetime                          
2014-9-24   0   0  1   0  0  0   0
2014-9-25   0   0  1   0  0  0   0
2014-9-26   0   1  0   0  0  0   0
2014-9-29   1   0  0   0  0  0   0
2014-9-30   1   0  0   0  0  0   0

# trainからweekとteperatureとweatherを抜き出し、ダミ－変数化したものを変数trainXに代入

In [100]:
trainX = pd.get_dummies(train[["week", "temperature", "weather"]])

# trainXの中身の確認

In [101]:
trainX.head()

temperature  week_月  week_木  week_水  week_火  week_金  weather_快晴  \
datetime                                                                      
2013-11-18         19.8       1       0       0       0       0           1   
2013-11-19         17.0       0       0       0       1       0           1   
2013-11-20         15.5       0       0       1       0       0           1   
2013-11-21         15.2       0       1       0       0       0           1   
2013-11-22         16.1       0       0       0       0       1           1   

            weather_晴れ  weather_曇  weather_薄曇  weather_雨  weather_雪  \
datetime                                                              
2013-11-18           0          0           0          0          0   
2013-11-19           0          0           0          0          0   
2013-11-20           0          0           0          0          0   
2013-11-21           0          0           0          0          0   
2013-11-22           0          0           0          0          0   

            weather_雷電  
datetime                
2013-11-18           0  
2013-11-19           0  
2013-11-20           0  
2013-11-21           0  
2013-11-22           0

# trainのdatetimeから年と月のデ－タを取り出し、trainの新たな列として追加

In [102]:
train["year"] = train["datetime"].apply(lambda x :x.split("-")[0])
train["month"] = train["datetime"].apply(lambda x :x.split("-")[1])

KeyError: 'datetime'

# testのdatetimeから年と月のデ－タを取り出し、testの新たな列として追加

In [90]:
test["year"] = test["datetime"].apply(lambda x :x.split("-")[0])
test["month"] = test["datetime"].apply(lambda x :x.split("-")[1])

KeyError: 'datetime'

# trainのデ－タの型を調べる

In [14]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 14 columns):
datetime         207 non-null object
y                207 non-null int64
week             207 non-null object
soldout          207 non-null int64
name             207 non-null object
kcal             166 non-null float64
remarks          21 non-null object
event            14 non-null object
payday           10 non-null float64
weather          207 non-null object
precipitation    207 non-null object
temperature      207 non-null float64
year             207 non-null object
month            207 non-null object
dtypes: float64(3), int64(2), object(9)
memory usage: 22.7+ KB


# train,testのデ－タの型を整数(int)に変換

In [15]:
# astype:元となるndarray(N-dimensional array)←N次元配列オブジェクト　をキャストし、コピーしたnadarrayを戻す
train["year"] = train["year"].astype(np.int)
train["month"] = train["month"].astype(np.int)
test["year"] =test["year"].astype(np.int)
test["month"] = test["month"].astype(np.int)


In [16]:
test.head()

datetime week  soldout        name   kcal remarks event  payday weather  \
0  2014-10-1    水        1       メンチカツ  420.0     NaN   NaN     NaN       雨   
1  2014-10-2    木        0   バーベキューチキン  415.0     NaN   NaN     NaN       曇   
2  2014-10-3    金        0  豚肉のマスタード焼き  405.0     NaN   NaN     NaN      晴れ   
3  2014-10-6    月        1        麻婆春雨  400.0     NaN   NaN     NaN       雨   
4  2014-10-7    火        0    厚揚げ肉みそ炒め  430.0     NaN   NaN     NaN      晴れ   

  precipitation  temperature  year  month  
0             0         20.2  2014     10  
1            --         23.9  2014     10  
2            --         28.7  2014     10  
3           0.5         21.5  2014     10  
4            --         22.1  2014     10

In [17]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 14 columns):
datetime         207 non-null object
y                207 non-null int64
week             207 non-null object
soldout          207 non-null int64
name             207 non-null object
kcal             166 non-null float64
remarks          21 non-null object
event            14 non-null object
payday           10 non-null float64
weather          207 non-null object
precipitation    207 non-null object
temperature      207 non-null float64
year             207 non-null int64
month            207 non-null int64
dtypes: float64(3), int64(4), object(7)
memory usage: 22.7+ KB


# train,testからyearとmonthを取り出し、変数trainX,testXに代入

In [18]:
trainX = train[["year", "month"]]
testX = test[["year", "month"]]

# trainXの中身の確認

In [19]:
trainX.head()

year  month
0  2013     11
1  2013     11
2  2013     11
3  2013     11
4  2013     11

# trainからyを取り出し、変数yに代入

In [20]:
y = train["y"]

In [21]:
model1 = LR()

In [22]:
# 説明変数trainXと目的変数y（販売数）で線形モデルの重みを学習し、線形回帰モデルを構築する
# 目的変数　＝　予測する対象
# 説明変数　＝　目的を予測するためのデータ
model1.fit(trainX, y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
model1.coef_

array([-104.0107109 ,   -7.41004428])

# 追加する特徴量検討の為に、trainXに対する予測値を変数predに代入

In [24]:
pred = model1.predict(trainX)

# predをtrainの新たな列predとして代入

In [25]:
train["pred"] =pred

# trainのyとpredを引き算した結果をtrainの新たな列resとして代入

In [26]:
train["res"] = train["y"] - train["pred"]

In [27]:
train.sort_values(by = "res").head()

datetime    y week  soldout         name   kcal remarks event  payday  \
27  2013-12-26   80    木        0           酢豚    NaN     NaN   NaN     NaN   
0   2013-11-18   90    月        0     厚切りイカフライ    NaN     NaN   NaN     NaN   
81   2014-3-26   51    水        0  肉団子クリームシチュー  392.0     NaN   NaN     NaN   
82   2014-3-27   55    木        1     ロース甘味噌焼き  315.0     NaN   NaN     NaN   
1   2013-11-19  101    火        1      手作りヒレカツ    NaN     NaN   NaN     NaN   

   weather precipitation  temperature  year  month        pred        res  
27       曇            --          7.3  2013     12  131.674984 -51.674984  
0       快晴            --         19.8  2013     11  139.085028 -49.085028  
81       曇            --         18.7  2014      3   94.354672 -43.354672  
82       曇           1.5         12.4  2014      3   94.354672 -39.354672  
1       快晴            --         17.0  2013     11  139.085028 -38.085028

In [28]:
trainX = train[["year", "month", "temperature"]].join(train["res"])
testX = test[["year", "month", "temperature"]].join(test["res"])

KeyError: 'res'

# 値が「お楽しみメニュー」であれば１、そうでなければ０とする自作関数を作る

In [29]:
def jisaku(x):
    if x == "お楽しみメニュー":
        return 1
    else:
        return 0    

# jisaku1関数とapply関数を使って、trainとtestの新たな列funを作る

In [30]:
train["fun"] = train["remarks"].apply(lambda x : jisaku(x))
test["fun"] = test["remarks"].apply(lambda x : jisaku(x))

In [31]:
train[train["remarks"]=="お楽しみメニュー"]

datetime    y week  soldout              name  kcal   remarks event  \
83   2014-3-28  106    金        0            キーマカレー   NaN  お楽しみメニュー   NaN   
93   2014-4-11  128    金        1            チキンカレー   NaN  お楽しみメニュー   NaN   
103  2014-4-25   80    金        0               中華丼   NaN  お楽しみメニュー   NaN   
115  2014-5-16  126    金        0            ポークカレー   NaN  お楽しみメニュー  ママの会   
125  2014-5-30  119    金        0            チキンカレー   NaN  お楽しみメニュー   NaN   
135  2014-6-13  121    金        0            キーマカレー   NaN  お楽しみメニュー   NaN   
145  2014-6-27   74    金        0                牛丼   NaN  お楽しみメニュー   NaN   
155  2014-7-11  124    金        0            ポークカレー   NaN  お楽しみメニュー   NaN   
164  2014-7-25   83    金        0  ひやしたぬきうどん・炊き込みご飯   NaN  お楽しみメニュー   NaN   
174   2014-8-8  129    金        0            チキンカレー   NaN  お楽しみメニュー   NaN   
181  2014-8-22  100    金        1             ロコモコ丼   NaN  お楽しみメニュー   NaN   
196  2014-9-12  115    金        0            ポークカレー   NaN  お楽しみメニュー   NaN   

     payday weather precipitation  temperature  year  month       pred  \
83      NaN      快晴            --         18.5  2014      3  94.354672   
93      NaN      快晴            --         16.5  2014      4  86.944628   
103     NaN      晴れ            --         20.8  2014      4  86.944628   
115     NaN      快晴            --         23.8  2014      5  79.534583   
125     NaN      薄曇            --         26.9  2014      5  79.534583   
135     NaN      晴れ            --         29.5  2014      6  72.124539   
145     NaN       雨             0         25.4  2014      6  72.124539   
155     NaN      晴れ            --         33.9  2014      7  64.714495   
164     NaN      晴れ            --         33.6  2014      7  64.714495   
174     1.0       曇            --         31.1  2014      8  57.304450   
181     NaN      晴れ            --         33.1  2014      8  57.304450   
196     NaN      晴れ            --         27.3  2014      9  49.894406   

           res  fun  
83   11.645328    1  
93   41.055372    1  
103  -6.944628    1  
115  46.465417    1  
125  39.465417    1  
135  48.875461    1  
145   1.875461    1  
155  59.285505    1  
164  18.285505    1  
174  71.695550    1  
181  42.695550    1  
196  65.105594    1

In [32]:
# カレーが重要そうである

In [33]:
train["curry"] = train["name"].apply(lambda x : 1 if x.find("カレー")>=0 else 0)

# 回答１
# train,testからyearとmonth、funとtemperatureの4カラムを取り出しtrainX,testXに代入
カラムを取り出 し、変数trainX,testXに代入

In [34]:
dummy = pd.get_dummies(train["weather"])
#pd.get_dummies( columns = train["weather"])

In [35]:
dummy.head()

快晴  晴れ  曇  薄曇  雨  雪  雷電
0   1   0  0   0  0  0   0
1   1   0  0   0  0  0   0
2   1   0  0   0  0  0   0
3   1   0  0   0  0  0   0
4   1   0  0   0  0  0   0

In [36]:
#dummy = dummy.drop(["雪","雷電"]) #KeyError: "['雪' '雷電'] not found in axis"

In [37]:
#train["weather"].replace(columns = train{"快晴":"fine weather"})

In [38]:
dummy = dummy.rename(columns={"快晴":"fineweather", "晴れ":"sunny", "曇":"cloudy", "薄曇":"lightcloudy", "雨":"rain", "雪":"snow","雷電":"raiden"})

In [39]:
dummy.head()

fineweather  sunny  cloudy  lightcloudy  rain  snow  raiden
0            1      0       0            0     0     0       0
1            1      0       0            0     0     0       0
2            1      0       0            0     0     0       0
3            1      0       0            0     0     0       0
4            1      0       0            0     0     0       0

In [40]:
trainX = train[["year", "month", "temperature","fun"]].join(dummy)
testX = test[["year", "month",  "temperature","fun"]].join(dummy)

In [41]:
trainX.head()

year  month  temperature  fun  fineweather  sunny  cloudy  lightcloudy  \
0  2013     11         19.8    0            1      0       0            0   
1  2013     11         17.0    0            1      0       0            0   
2  2013     11         15.5    0            1      0       0            0   
3  2013     11         15.2    0            1      0       0            0   
4  2013     11         16.1    0            1      0       0            0   

   rain  snow  raiden  
0     0     0       0  
1     0     0       0  
2     0     0       0  
3     0     0       0  
4     0     0       0

In [42]:
testX.head()

year  month  temperature  fun  fineweather  sunny  cloudy  lightcloudy  \
0  2014     10         20.2    0            1      0       0            0   
1  2014     10         23.9    0            1      0       0            0   
2  2014     10         28.7    0            1      0       0            0   
3  2014     10         21.5    0            1      0       0            0   
4  2014     10         22.1    0            1      0       0            0   

   rain  snow  raiden  
0     0     0       0  
1     0     0       0  
2     0     0       0  
3     0     0       0  
4     0     0       0

In [43]:
trainX.shape

(207, 11)

In [44]:
testX.shape

(40, 11)

In [45]:
y.shape

(207,)

In [77]:
trainX.drop(["label", "0"], axis = 1).head()

KeyError: "['label' '0'] not found in axis"

In [49]:
model7 = LR()

In [50]:
model7.fit(trainX, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [51]:
model7.coef_ #傾き

array([-76.20819388,  -4.16842097,  -1.34740486,  44.8565549 ,
         5.44633039,   8.6629392 ,   7.94831761,   8.55426543,
         7.38381334, -21.2423677 , -16.75329827])

In [52]:
model7.intercept_ #切片

153600.49857138566

In [53]:
pred4 = model7.predict(testX)

In [54]:
sample[3] = pred4

In [55]:
sample.to_csv("submit11.csv", index = None, header = None)

# 天気をone hot encodingし全体に結合

In [56]:
dummy_trainX = pd.concat([train,train["weather"].str.get_dummies(sep = " | ")], axis = 1)
dummy_testX = pd.concat([test,test["weather"].str.get_dummies(sep = " | ")], axis = 1)

In [57]:
dummy_trainX.head()

datetime    y week  soldout        name  kcal remarks event  payday  \
0  2013-11-18   90    月        0    厚切りイカフライ   NaN     NaN   NaN     NaN   
1  2013-11-19  101    火        1     手作りヒレカツ   NaN     NaN   NaN     NaN   
2  2013-11-20  118    水        0  白身魚唐揚げ野菜あん   NaN     NaN   NaN     NaN   
3  2013-11-21  120    木        1      若鶏ピリ辛焼   NaN     NaN   NaN     NaN   
4  2013-11-22  130    金        1    ビッグメンチカツ   NaN     NaN   NaN     NaN   

  weather ... fun  curry  |  快晴  晴れ  曇  薄曇  雨  雪  雷電  
0      快晴 ...   0      0  0   1   0  0   0  0  0   0  
1      快晴 ...   0      0  0   1   0  0   0  0  0   0  
2      快晴 ...   0      0  0   1   0  0   0  0  0   0  
3      快晴 ...   0      0  0   1   0  0   0  0  0   0  
4      快晴 ...   0      0  0   1   0  0   0  0  0   0  

[5 rows x 26 columns]

# この場合weatherのみone hot encodingされ、前で処理したyear,monthが元に戻っている

# 回答２（エラーが出ている）

In [58]:
dummy = train["weather"].str.get_dummies(sep = "|")

In [59]:
trainX = train[["year", "month", "temperature","weather"]]
testX = test[["year", "month", "temperature","weather"]]

In [60]:
#pd.merge(trainX,train["dummy"])

In [61]:
#trainX1 = pd.concat([trainX,train["weather"].str.get_dummies(sep = "|")], axis = 1) # axis=1 水平
trainX1 = pd.concat([trainX, dummy], axis = 1) # axis=1 水平
testX1 = pd.concat([testX,dummy], axis = 1)

In [62]:
trai.keys() >= 

SyntaxError: invalid syntax (<ipython-input-62-222aa3289450>, line 1)

In [63]:
trainX1.head()

year  month  temperature weather  快晴  晴れ  曇  薄曇  雨  雪  雷電
0  2013     11         19.8      快晴   1   0  0   0  0  0   0
1  2013     11         17.0      快晴   1   0  0   0  0  0   0
2  2013     11         15.5      快晴   1   0  0   0  0  0   0
3  2013     11         15.2      快晴   1   0  0   0  0  0   0
4  2013     11         16.1      快晴   1   0  0   0  0  0   0

In [64]:
model8 = LR()

In [65]:
model8.fit(trainX1, y)

ValueError: could not convert string to float: '快晴'

In [66]:
# weatherをone hot encodingしてもtrainXにweatherを入れるとweatherは文字なのでcould not convert string to float: '快晴'　とエラーがでる

# 回答３

In [67]:
dummy = train["weather"].str.get_dummies(sep = "|")

In [68]:
dummy = dummy.rename(columns={"快晴":"fineweather", "晴れ":"sunny", "曇":"cloudy", "薄曇":"lightcloudy", "雨":"rain", "雪":"snow","雷電":"raiden"})

In [69]:
dummy.head()

fineweather  sunny  cloudy  lightcloudy  rain  snow  raiden
0            1      0       0            0     0     0       0
1            1      0       0            0     0     0       0
2            1      0       0            0     0     0       0
3            1      0       0            0     0     0       0
4            1      0       0            0     0     0       0

In [70]:
trainX = train[["year", "month", "temperature"]]
testX = test[["year", "month", "temperature"]]

In [71]:
trainX.head()

year  month  temperature
0  2013     11         19.8
1  2013     11         17.0
2  2013     11         15.5
3  2013     11         15.2
4  2013     11         16.1

In [72]:
testX.head()

year  month  temperature
0  2014     10         20.2
1  2014     10         23.9
2  2014     10         28.7
3  2014     10         21.5
4  2014     10         22.1

In [70]:
trainX1 = pd.concat([trainX,dummy],axis=1) # axis=1 水平 # dummy代入
testX1 = pd.concat([testX,dummy],axis=1)
#trainX1 = pd.concat([trainX,dummy.rename(columns={"快晴":"fineweather", "晴れ":"sunny", "曇":"cloudy", "薄曇":"lightcloudy", "雨":"rain", "雪":"snow","雷電":"raiden"}),axis=1)
#testX1 = pd.concat([testX,dummy.rename(columns={"快晴":"fineweather", "晴れ":"sunny", "曇":"cloudy", "薄曇":"lightcloudy", "雨":"rain", "雪":"snow","雷電":"raiden"}),axis=1)                     

In [71]:
trainX1.head()

year  month  temperature  fineweather  sunny  cloudy  lightcloudy  rain  \
0  2013     11         19.8            1      0       0            0     0   
1  2013     11         17.0            1      0       0            0     0   
2  2013     11         15.5            1      0       0            0     0   
3  2013     11         15.2            1      0       0            0     0   
4  2013     11         16.1            1      0       0            0     0   

   snow  raiden  
0     0       0  
1     0       0  
2     0       0  
3     0       0  
4     0       0

In [72]:
testX1.head()

year  month  temperature  fineweather  sunny  cloudy  lightcloudy  rain  \
0  2014.0   10.0         20.2            1      0       0            0     0   
1  2014.0   10.0         23.9            1      0       0            0     0   
2  2014.0   10.0         28.7            1      0       0            0     0   
3  2014.0   10.0         21.5            1      0       0            0     0   
4  2014.0   10.0         22.1            1      0       0            0     0   

   snow  raiden  
0     0       0  
1     0       0  
2     0       0  
3     0       0  
4     0       0

In [73]:
model9 = LR()

In [74]:
model9.fit(trainX1, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [75]:
model9.coef_ #傾き

array([-81.87873807,  -4.99343573,  -0.8889148 ,   6.30901071,
        10.14590512,   7.17126729,   6.1442749 ,   7.35017692,
       -17.9618128 , -19.15882213])

In [76]:
model9.intercept_ #切片

165018.79384544928

In [77]:
pred2 = model9.predict(testX1)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [78]:
# shapes (40,8) and (10,) not aligned: 8 (dim 1) != 10 (dim 0) かける列数が違う

In [79]:
#Input contains NaN, infinity or a value too large for dtype('float64').

In [80]:
sample.to_csv("submit13.csv", index = None, header = None)

# 回答４

In [81]:
dummy = train["weather"].str.get_dummies(sep = "|")

In [82]:
dummy = dummy.rename(columns={"快晴":"fineweather", "晴れ":"sunny", "曇":"cloudy", "薄曇":"lightcloudy", "雨":"rain", "雪":"snow","雷電":"raiden"})

In [83]:
dummy.head()

fineweather  sunny  cloudy  lightcloudy  rain  snow  raiden
0            1      0       0            0     0     0       0
1            1      0       0            0     0     0       0
2            1      0       0            0     0     0       0
3            1      0       0            0     0     0       0
4            1      0       0            0     0     0       0

In [84]:
trainX1 = trainX.append(dummy)
testX1 = testX.append(dummy)

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


# 回答５

## train,testからyearとmonth、funとtemperatureの4カラムを取り出し、変数trainX,testXに代入

In [85]:
trainX = train[["year", "month", "fun", "temperature"]]
testX = test[["year", "month", "fun", "temperature"]]

In [86]:
model2 = LR()

In [87]:
model2.fit(trainX, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [88]:
model2.coef_ #傾き

array([-76.3765687 ,  -4.20489757,  44.63348171,  -1.25463854])

In [89]:
model2.intercept_ #切片

153945.2541175833

In [90]:
pred2 = model2.predict(testX)

In [91]:
sample[1] = pred2

In [92]:
sample.to_csv("submit5.csv", index = None, header = None)

# 回答６

# train,testからyearとmonthとtemperatureの３カラムを取り出し、変数trainX,testXに代入

In [93]:
trainX = train[["year", "month",  "temperature"]]
testX = test[["year", "month", "temperature"]]

In [94]:
model3 = LR()

In [95]:
model3.fit(trainX, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [96]:
model3.coef_ #傾き

array([-83.20224329,  -5.14775581,  -0.77874006])

In [97]:
model3.intercept_ #切片

167690.2673254738

In [98]:
pred2 = model3.predict(testX)

In [99]:
sample[1] = pred2

In [100]:
sample.to_csv("submit6.csv", index = None, header = None)

# 回答７

In [101]:
dummy1 = pd.get_dummies(train["week"])

In [102]:
dummy1.head()

月  木  水  火  金
0  1  0  0  0  0
1  0  0  0  1  0
2  0  0  1  0  0
3  0  1  0  0  0
4  0  0  0  0  1

In [103]:
trainX = train[["year", "month",  "temperature"]].join([dummy1])
testX = test[["year", "month", "temperature"]].join([dummy1])

In [104]:
model3 = LR()

In [105]:
model3.fit(trainX, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [106]:
model3.coef_ #傾き

array([-81.91215632,  -4.99991522,  -0.84650207,   8.33030683,
        -8.7725092 ,  -1.52383272,   0.47664597,   1.48938912])

In [107]:
model3.intercept_ #切片

165092.81272229186

In [108]:
pred2 = model3.predict(testX)

In [109]:
sample[1] = pred2

In [110]:
sample.to_csv("submit12.csv", index = None, header = None)

# 回答８

In [111]:
#train["月”] = train["week"].apply(lambda x : x.split(","))

In [112]:
def monday(x):# 引数をxとして関数mondayを定義する。月曜日があったら１、無かったら０を返す
    if x == "月":
        return 1
    else:
        return 0    

In [113]:
train["月"] = train["remarks"].apply(lambda x : monday(x))#  apply関数　＝　各値に数式や関数を適用するための関数
test["月"] = test["remarks"].apply(lambda x : monday(x))# lambda 　引数：処理内容
# カラム"remarks"にapply関数を使ってmonday関数を適用する。train,testの新たなカラム「月」を作る。
# monday関数を適用しているのでカラム「月」に、月曜日なら１がたつ

In [114]:
trainX = train[["year", "month",  "temperature", "月"]]# train,testからyear,month,temperature,月の４カラムを取り出し変数trainX,testXに代入
testX = test[["year", "month", "temperature", "月"]]

In [115]:
model4 = LR()# 線形回帰(LR)を変数model4とおく　# LR ＝　LinearRegression　

In [116]:
model4.fit(trainX, y)# 説明変数trainXと目的変数y（販売数）で線形モデルの重みを学習し、線形回帰モデルを構築する
# 目的変数　＝　予測する対象
# 説明変数　＝　目的を予測するためのデータ

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [117]:
model4.coef_ #傾き # 作ったモデルの傾きを求める

array([-83.20224329,  -5.14775581,  -0.77874006,   0.        ])

In [118]:
model4.intercept_ #切片 # 作ったモデル（回帰直線）の切片を求める

167690.26732547366

In [119]:
pred2 = model4.predict(testX) # 線形モデルから目的変数（販売数）を予測

In [120]:
sample[1] = pred2# pred2をsample[1]に代入

In [121]:
sample.to_csv("submit7.csv", index = None, header = None)# 答え（CSVファイル）を作成

# 回答９

In [122]:
def hare(x):# 引数をxとして関数mondayを定義する。晴があったら１、無かったら０を返す
    if x == "晴":
        return 1
    else:
        return 0 

In [123]:
train["晴"] = train["remarks"].apply(lambda x : hare(x))# カラム"remarks"にapply関数を使ってhare関数を適用する。train,testの新たなカラム「晴」を作る。
test["晴"] = test["remarks"].apply(lambda x : hare(x))# hare関数を適用しているのでカラム「晴」に、晴なら１がたつ

In [124]:
trainX = train[["year", "month",  "temperature", "晴"]]# train,testからyear,month,temperature,晴の４カラムを取り出し変数trainX,testXに代入
testX = test[["year", "month", "temperature", "晴"]]

In [125]:
model5 = LR()# 線形回帰(LR)を変数model５とおく

In [126]:
model5.fit(trainX, y)# 説明変数trainXと目的変数y（販売数）で線形モデルの重みを学習し、線形回帰モデルを構築する

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [127]:
model5.coef_ #傾き# 作ったモデルの傾きを求める

array([-83.20224329,  -5.14775581,  -0.77874006,   0.        ])

In [128]:
model5.intercept_ #切片# 作ったモデル（回帰直線）の切片を求める

167690.26732547366

# 回答１０

In [129]:
def monday(x):# 引数をxとして関数mondayを定義する。月曜日があったら１、無かったら０を返す
    if x == "月":
        return 1
    else:
        return 0

In [130]:
train["月"] = train["week"].apply(lambda x : monday(x))# カラム"remarks"にapply関数を使ってweek関数を適用する。train,testの新たなカラム「月」を作る。
test["月"] = test["week"].apply(lambda x : monday(x))# week関数を適用しているのでカラム「月」に、月曜日なら１がたつ

In [131]:
trainX = train[["year", "month", "temperature","月"]]# train,testからyear,month,temperature,月の４カラムを取り出し変数trainX,testXに代入
testX = test[["year", "month", "temperature","月"]]

In [132]:
model6 = LR()# 線形回帰(LR)を変数model6とおく

In [133]:
model6.fit(trainX, y)# 説明変数trainXと目的変数y（販売数）で線形モデルの重みを学習し、線形回帰モデルを構築する

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [134]:
model6.coef_ #傾き# 作ったモデルの傾きを求める

array([-83.18303971,  -5.14060556,  -0.79078836,  10.47478481])

In [135]:
model6.intercept_ #切片 # 作ったモデル（回帰直線）の切片を求める

167649.8098594403

In [136]:
pred2 = model6.predict(testX)# 線形モデルから目的変数（販売数）を予測

In [137]:
sample[1] = pred2# pred2をsample[1]に代入

In [138]:
sample.to_csv("submit9.csv", index = None, header = None)# 答え（CSVファイル）を作成